version: 2.1

jobs:
  record_changes:
    docker:
      - image: "circleci/node:9.6.1"
    description: "Record changes and persist result to workspace"
    steps:
      - run: echo "export FILE_A=0" > '/tmp/load_change_status.sh'
      - run: echo "export FILE_B=1" >> '/tmp/load_change_status.sh'
      - persist_to_workspace:
          root: /tmp
          paths:
            - load_change_status.sh
  build:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - attach_workspace:
          at: /tmp
      - run: cat /tmp/load_change_status.sh >> $BASH_ENV
#      - run: source /tmp/load_change_status.sh && echo ${FOO}
      - run: echo ${FOO}
      - run: cat $BASH_ENV

