version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: |
          curl -H "Authorization: token ${PERSONAL_ACCESS_TOKEN}" \
               -H "Accept: application/vnd.github.VERSION.patch" \
               https://api.github.com/repos/annapamma/training_01_Hello_World/pulls/2 > pr.txt
      - run: cat pr.txt
      - store_artifacts:
          path: pr.txt
          destination: pr-file-changes

workflows:
  version: 2
  test:
    jobs:
        - build:
            context: remotecachedemo
