version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: |
          echo $CIRCLE_BUILD_NUM
  step2:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: |
          echo $CIRCLE_WORKFLOW_ID

workflows:
  version: 2
  test:
    jobs:
        - build
        - step2
