version: 2.1

commands:
  record_changes:
    steps:
      - run: echo 'there were changes' > '/tmp/check_for_changes.txt'
      - persist_to_workspace:
          root: /tmp
          paths:
            - check_for_changes.txt
  check_for_changes:
    steps:
      - run: |
          CHANGES=`cat /tmp/check_for_changes.txt | awk '{print length}'`
          echo ${CHANGES}
          if [[ CHANGES > 0 ]]
          then
            echo "file has contents"
          else
            echo "file is empty"
          fi

  run_downstream_jobs:
    description: "A very simple command for demonstration purposes"
    # if changes, add to a file
    # read that file
    steps:
      - run: echo "ran downstream jobs"

jobs:
  build:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - record_changes
      - check_for_changes
