version: 2.1

jobs:
  record_changes:
    docker:
      - image: "circleci/node:9.6.1"
    description: "Record changes and persist result to workspace"
    steps:
      - run: echo 'there were changes' > '/tmp/check_for_changes.txt'
      - persist_to_workspace:
          root: /tmp
          paths:
            - check_for_changes.txt
  check_for_changes:
    docker:
      - image: "circleci/node:9.6.1"
    description: "Check for changes"
    steps:
      - run: |
          CHANGES=`cat /tmp/check_for_changes.txt | awk '{print length}'`
          if [[ ${#CHANGES} -gt 0 ]]
          then
            echo "file has contents"
          else
            echo "file is empty"
          fi


workflows:
  test:
    jobs:
      - record_changes
      - check_for_changes:
          requires:
            - record_changes
