version: 2.1

commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      expected-changes:
        type: string
        default: "True"
      to:
        type: string
        default: "no one"
    steps:
      - run: echo << parameters.to >>
      - run: |
          if [ ! expected-changes ]; then
              circleci-agent step halt
          fi

jobs:
  build:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - sayhello:
          to: "Lev"

