version: 2
jobs:
  build:
    parameters:
      test:
        type: string
        default: "goodbye"
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hello world"
      - run: echo << parameters.test >>
