version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk@sha256:9382a070f79220a7474f01969240427b0a1df805ffee02c082cacd1ba4d1d636
    steps:
      - checkout
      - run: echo "hello world"
      - run: echo $(git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master))
# add test branch