version: 2.1

jobs:

  record_changes:
    docker:
      - image: "circleci/node:9.6.1"
    description: "Record changes and persist result to workspace"
    steps:
      - run:
          echo 'export CHANGES=HELLO' > '/tmp/load_change_status.sh'
      - persist_to_workspace:
          root: /tmp
          paths:
            - load_change_status.sh

#  check_for_changes:
#    docker:
#      - image: "circleci/node:9.6.1"
#    description: "Check for changes"
#    steps:
#      - attach_workspace:
#          at: /tmp
#      - run: |
#          CHANGES=`cat /tmp/check_for_changes.txt | awk '{print length}'`
#          if [[ ${#CHANGES} -gt 0 ]]
#          then
#            echo "There were changes"
#            exit 0
#          else
#            echo "There were no changes"
#            exit 1
#          fi

  downstream_job:
    docker:
      - image: "circleci/node:9.6.1"
    description: "Only run if there are changes"
    steps:
#      - attach_workspace:
#          at: /tmp
      - run: echo 'export CHANGES="HELLO"' > '/tmp/load_change_status.sh'
      - run: source /tmp/load_change_status.sh
      - run:  |
          cat /tmp/load_change_status.sh
          echo ${CHANGES}

#          if [[ ${CHANGES} == 'HELLO' ]]
#          then
#            echo 'woo'
#          else
#            echo 'fail'
#          fi
#      - run: echo "downstream job ran"

workflows:
  test:
    jobs:
      - downstream_job
#      - record_changes
#      - downstream_job:
#          requires:
#            - record_changes
