version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk@sha256:9382a070f79220a7474f01969240427b0a1df805ffee02c082cacd1ba4d1d636
    steps:
      - checkout
      - run: |
          curl https://patch-diff.githubusercontent.com/raw/:owner/:reponame/pull/:prid.patch > pr.txt
      - run: cat pr.txt
      - store_artifacts:
          path: pr.txt
          destination: pr-file-changes
# 1