#version: 2
#jobs:
#  build:
#    docker:
#      - image: circleci/node
#    resource_class: small
#    steps:
#      - checkout
#      - run: |
#          echo $CIRCLE_BUILD_NUM
#  step2:
#    docker:
#      - image: circleci/node
#    resource_class: medium
#    steps:
#      - checkout
#      - run: |
#          echo $CIRCLE_WORKFLOW_ID
#
#workflows:
#  version: 2
#  test:
#    jobs:
#        - build
#        - step2
version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: bash.exe
    steps:
      - checkout
      - run: ls -lah
      - run:
          command: .\build.ps1
          shell: powershell.exe