version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk@sha256:9382a070f79220a7474f01969240427b0a1df805ffee02c082cacd1ba4d1d636
    steps:
      - checkout
      - run: echo "hello world"
      - run: ls
      - run: |
          curl https://patch-diff.githubusercontent.com/raw/annapamma/training_01_Hello_World/pull/1.patch > pr.txt
      - run: cat pr.txt
     - store_artifacts:
       path: pr.txt
       destination: pr-file-changes
# add test branch