version: 2
jobs:
  build:
    parameters:
      test:
        type: string
        default: "goodbye"
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "hello world"
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir -p /tmp/1/artifacts;
            echo "my artifact files in a dir" > /tmp/1/artifacts/artifact-file;
            mkdir tmp/artifacts
            cp tmp/**/artifacts/ tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
